linters-settings:
  gosec:
    severity: "medium"
  cyclop:
    max-complexity: 10
    ignore-tests: true
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - cyclop
    - dupl
    - gci
    - goconst
    - gocritic
    - godox
    - gofmt
    - gosec
    - revive
run:
  timeout: 5m
issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - errcheck
